# Repository header: begin
# Provenance source mode: source_refs
# Provenance source refs:
# - 000010#repo.config.python.active-src-package-boundary
# - 000017#repo.code.architecture.vertical-slices-and-cqrs.repo-wide
# - 001040#repo.runtime.target-modular-layout.bounded-contexts
# - 001046#repo.blueprint-validation.validator-policy
# License notice ref: 000015#repo.headers.license.mit-notice.exact-block
# Copyright (c) 2026 Alberto Villa Osorno.
# Licensed under the MIT License. See LICENSE in the project root.
# Repository header: end

"""Make blueprint validation slice boundary.

Boundary contract:
- Owns: the public import surface for blueprint validation capabilities.
- Must not: implement validation rules, catalog traversal, or rendering gates.
- Allows: re-exporting stable validation models and owned functions.
- Split when: exports require compatibility adapters or optional integrations.
- Merge when another package marker duplicates this validation API surface.
"""

from __future__ import annotations

from blueprints.validation.ai_review import (
    AiReviewError,
    bounded_review_text,
    build_minimal_content_review,
    decode_text_content,
    extract_json_object,
    reject_server_side_ai,
    validate_content_review,
)
from blueprints.validation.assisted_delivery_capture import (
    AssistedDeliveryCaptureValidation,
    validate_assisted_delivery_capture,
)
from blueprints.validation.client_report import (
    ClientSafeAuditReport,
    ClientSafeReportAudience,
    ClientSafeReportPdfStatus,
    build_client_safe_audit_report,
    client_safe_audit_report_as_dict,
    client_safe_audit_report_guard_errors,
    render_operator_report_preview,
)
from blueprints.validation.delivery_coverage import (
    BlueprintDeliveryCoverage,
    build_blueprint_delivery_coverage,
    coverage_regressed,
)
from blueprints.validation.delivery_mode import (
    BlueprintDeliveryMode,
    achieved_blueprint_delivery_mode,
)
from blueprints.validation.generation_gate import guard_blueprint_for_render
from blueprints.validation.handoff_manifest import (
    HandoffPlaceholder,
    HandoffReplacementPath,
    build_handoff_placeholder_manifest,
)
from blueprints.validation.handoff_policy import (
    DEFAULT_EXISTING_AST_LEGACY_POLICY,
    DEFAULT_GENERATION_LEGACY_POLICY,
    DEFAULT_QUALITY_PROFILE,
    FieldBindingKind,
    HandoffQualityProfile,
    LegacyModulePolicy,
    choose_catalog_field_seed_value,
    classify_catalog_field_binding,
    is_unresolved_handoff_value,
    normalize_legacy_policy,
    normalize_quality_profile,
)
from blueprints.validation.identity import SLICE_NAME
from blueprints.validation.intake import (
    CLIENT_BLUEPRINT_REQUIRED_MANIFEST_FIELDS,
    MAX_CLIENT_BLUEPRINT_BYTES,
    ClientBlueprintArtifactType,
    ClientBlueprintDeletionStatus,
    ClientBlueprintEvidenceCoverageStatus,
    ClientBlueprintFindingClass,
    ClientBlueprintFindingSeverity,
    ClientBlueprintIntakeDecision,
    ClientBlueprintIntakeFinding,
    ClientBlueprintIntakeManifest,
    ClientBlueprintIntakeMethod,
    ClientBlueprintIntakeRequest,
    ClientBlueprintLocalAnalysisBoundary,
    ClientBlueprintPersonalDataStatus,
    ClientBlueprintPublicBackendExposure,
    ClientBlueprintRedactionStatus,
    ClientBlueprintSecretStatus,
    ClientBlueprintShapeStatus,
    ClientBlueprintSourceType,
    ClientBlueprintTruncationReason,
    client_blueprint_intake_manifest_as_dict,
    client_blueprint_report_release_errors,
    mark_client_blueprint_source_deleted,
    validate_client_blueprint_intake,
)
from blueprints.validation.linter_rule_ast_guard import (
    LinterRuleAstGuardReport,
    validate_linter_predicate_source,
)
from blueprints.validation.linter_rule_intake import (
    MAKE_LINTER_CANDIDATE_DECISIONS,
    MAKE_LINTER_EVIDENCE_SURFACES,
    MAKE_LINTER_INTAKE_REQUIREMENTS,
    MAKE_LINTER_PROFILE_GATES,
    MAKE_LINTER_PROMOTED_DECISIONS,
    MAKE_LINTER_PROMOTION_AUDIENCES,
    MAKE_LINTER_PROMOTION_READINESS_REQUIRED_FIELDS,
    MAKE_LINTER_PROMOTION_SURFACES,
    MAKE_LINTER_REVIEW_REQUIRED_FIELDS,
    MAKE_LINTER_SEVERITY_POSTURES,
    MAKE_LINTER_SEVERITY_TRANSITIONS,
    MakeLinterCandidateDecision,
    MakeLinterCandidateReviewRecord,
    MakeLinterEvidenceSurface,
    MakeLinterIntakeRequirement,
    MakeLinterProfileGate,
    MakeLinterPromotionAudience,
    MakeLinterPromotionReadinessRecord,
    MakeLinterPromotionSurface,
    MakeLinterSeverityPosture,
    MakeLinterSeverityTransition,
    make_linter_intake_requirements,
    make_linter_promotion_readiness_errors,
    make_linter_review_record_errors,
)
from blueprints.validation.linter_sqlite_audit import (
    LINTER_AUDIT_SOURCE_OF_TRUTH,
    LINTER_DATA_INVENTORY_SOURCE_OF_TRUTH,
    LinterDataSourceInventoryRow,
    LinterRuleSurface,
    LinterRuleSurfaceMatrixRow,
    LinterSQLiteAuditReport,
    linter_data_source_inventory,
    linter_rule_surface_matrix,
    sync_linter_sqlite_audit,
)
from blueprints.validation.linter_taxonomy import (
    MAKE_LINTER_RULE_FAMILIES,
    MAKE_LINTER_RULE_FAMILY_IDS,
    MakeLinterEvidenceSource,
    MakeLinterGateBehavior,
    MakeLinterRuleFamily,
    MakeLinterRuleFamilyId,
    make_linter_rule_families,
    make_linter_rule_family_by_id,
    make_linter_rule_family_for_code,
    make_linter_supported_codes,
)
from blueprints.validation.local_parity import (
    LOCAL_BLUEPRINT_PARITY_AREAS,
    LOCAL_BLUEPRINT_PARITY_LIVE_CALLS_REQUIRED,
    LocalBlueprintParityArea,
    LocalBlueprintParityEvidence,
    LocalBlueprintParityFailure,
    LocalBlueprintParityReport,
    LocalBlueprintParityReportStatus,
    LocalBlueprintParityStatus,
    validate_local_blueprint_import_parity,
)
from blueprints.validation.models import (
    BLUEPRINT_DELTA_CATEGORIES,
    FINDING_SEVERITIES,
    BlueprintDeltaCategory,
    BlueprintFindingSeverity,
    BlueprintGenerationBlocker,
    BlueprintGenerationGateReport,
    BlueprintGenerationGateStatus,
    BlueprintValidationFinding,
    BlueprintValidationReport,
)
from blueprints.validation.note_reference_contract import (
    COLOR_CAPABLE_SURFACES,
    MAKE_HEX_COLOR_PATTERN,
    NOTE_REFERENCE_CODE_PREFIX,
    NoteReferenceColorEvidence,
    NoteReferenceSurface,
    TechnicalPdfNoteReference,
    TechnicalPdfNoteReferenceDraft,
    build_technical_pdf_note_references,
    technical_pdf_note_reference_code_map,
)
from blueprints.validation.note_surfaces import (
    NOTE_GUIDANCE_STATEMENTS,
    NOTE_SURFACE_DEFINITIONS,
    NoteGuidanceStatement,
    NoteGuidanceStatus,
    NoteSurfaceDefinition,
    NoteSurfaceKind,
    classify_note_surface,
    note_guidance_statements,
    note_surface_definition_by_kind,
    note_surface_definitions,
)
from blueprints.validation.public_demo_score import (
    PUBLIC_DEMO_AGGREGATE_SCORE_FIELDS,
    PublicDemoAggregateScore,
    PublicDemoFormatStatus,
    PublicDemoRiskBand,
    blocked_public_demo_aggregate_score,
    build_public_demo_aggregate_score,
    public_demo_aggregate_score_as_dict,
)
from blueprints.validation.scenario_rule_taxonomy import (
    SCENARIO_RULE_SURFACE_IDS,
    SCENARIO_RULE_SURFACES,
    ScenarioRuleEvidenceGate,
    ScenarioRuleOutputPosture,
    ScenarioRuleSignalDomain,
    ScenarioRuleSurface,
    ScenarioRuleSurfaceId,
    scenario_rule_surface_by_id,
    scenario_rule_surface_ids,
    scenario_rule_surfaces,
)
from blueprints.validation.setup_readiness import (
    SETUP_READINESS_BLOCKER,
    SETUP_READINESS_BLOCKER_CODE,
    SetupReadinessDimension,
    SetupReadinessFinding,
    SetupReadinessReport,
    SetupReadinessSource,
    check_setup_readiness,
    setup_readiness_completion_blockers,
)
from blueprints.validation.validator import validate_blueprint

__all__ = (
    "BLUEPRINT_DELTA_CATEGORIES",
    "CLIENT_BLUEPRINT_REQUIRED_MANIFEST_FIELDS",
    "COLOR_CAPABLE_SURFACES",
    "DEFAULT_EXISTING_AST_LEGACY_POLICY",
    "DEFAULT_GENERATION_LEGACY_POLICY",
    "DEFAULT_QUALITY_PROFILE",
    "FINDING_SEVERITIES",
    "LINTER_AUDIT_SOURCE_OF_TRUTH",
    "LINTER_DATA_INVENTORY_SOURCE_OF_TRUTH",
    "LOCAL_BLUEPRINT_PARITY_AREAS",
    "LOCAL_BLUEPRINT_PARITY_LIVE_CALLS_REQUIRED",
    "MAKE_HEX_COLOR_PATTERN",
    "MAKE_LINTER_CANDIDATE_DECISIONS",
    "MAKE_LINTER_EVIDENCE_SURFACES",
    "MAKE_LINTER_INTAKE_REQUIREMENTS",
    "MAKE_LINTER_PROFILE_GATES",
    "MAKE_LINTER_PROMOTED_DECISIONS",
    "MAKE_LINTER_PROMOTION_AUDIENCES",
    "MAKE_LINTER_PROMOTION_READINESS_REQUIRED_FIELDS",
    "MAKE_LINTER_PROMOTION_SURFACES",
    "MAKE_LINTER_REVIEW_REQUIRED_FIELDS",
    "MAKE_LINTER_RULE_FAMILIES",
    "MAKE_LINTER_RULE_FAMILY_IDS",
    "MAKE_LINTER_SEVERITY_POSTURES",
    "MAKE_LINTER_SEVERITY_TRANSITIONS",
    "MAX_CLIENT_BLUEPRINT_BYTES",
    "NOTE_GUIDANCE_STATEMENTS",
    "NOTE_REFERENCE_CODE_PREFIX",
    "NOTE_SURFACE_DEFINITIONS",
    "PUBLIC_DEMO_AGGREGATE_SCORE_FIELDS",
    "SCENARIO_RULE_SURFACES",
    "SCENARIO_RULE_SURFACE_IDS",
    "SETUP_READINESS_BLOCKER",
    "SETUP_READINESS_BLOCKER_CODE",
    "SLICE_NAME",
    "AiReviewError",
    "AssistedDeliveryCaptureValidation",
    "BlueprintDeliveryCoverage",
    "BlueprintDeliveryMode",
    "BlueprintDeltaCategory",
    "BlueprintFindingSeverity",
    "BlueprintGenerationBlocker",
    "BlueprintGenerationGateReport",
    "BlueprintGenerationGateStatus",
    "BlueprintValidationFinding",
    "BlueprintValidationReport",
    "ClientBlueprintArtifactType",
    "ClientBlueprintDeletionStatus",
    "ClientBlueprintEvidenceCoverageStatus",
    "ClientBlueprintFindingClass",
    "ClientBlueprintFindingSeverity",
    "ClientBlueprintIntakeDecision",
    "ClientBlueprintIntakeFinding",
    "ClientBlueprintIntakeManifest",
    "ClientBlueprintIntakeMethod",
    "ClientBlueprintIntakeRequest",
    "ClientBlueprintLocalAnalysisBoundary",
    "ClientBlueprintPersonalDataStatus",
    "ClientBlueprintPublicBackendExposure",
    "ClientBlueprintRedactionStatus",
    "ClientBlueprintSecretStatus",
    "ClientBlueprintShapeStatus",
    "ClientBlueprintSourceType",
    "ClientBlueprintTruncationReason",
    "ClientSafeAuditReport",
    "ClientSafeReportAudience",
    "ClientSafeReportPdfStatus",
    "FieldBindingKind",
    "HandoffPlaceholder",
    "HandoffQualityProfile",
    "HandoffReplacementPath",
    "LegacyModulePolicy",
    "LinterDataSourceInventoryRow",
    "LinterRuleAstGuardReport",
    "LinterRuleSurface",
    "LinterRuleSurfaceMatrixRow",
    "LinterSQLiteAuditReport",
    "LocalBlueprintParityArea",
    "LocalBlueprintParityEvidence",
    "LocalBlueprintParityFailure",
    "LocalBlueprintParityReport",
    "LocalBlueprintParityReportStatus",
    "LocalBlueprintParityStatus",
    "MakeLinterCandidateDecision",
    "MakeLinterCandidateReviewRecord",
    "MakeLinterEvidenceSource",
    "MakeLinterEvidenceSurface",
    "MakeLinterGateBehavior",
    "MakeLinterIntakeRequirement",
    "MakeLinterProfileGate",
    "MakeLinterPromotionAudience",
    "MakeLinterPromotionReadinessRecord",
    "MakeLinterPromotionSurface",
    "MakeLinterRuleFamily",
    "MakeLinterRuleFamilyId",
    "MakeLinterSeverityPosture",
    "MakeLinterSeverityTransition",
    "NoteGuidanceStatement",
    "NoteGuidanceStatus",
    "NoteReferenceColorEvidence",
    "NoteReferenceSurface",
    "NoteSurfaceDefinition",
    "NoteSurfaceKind",
    "PublicDemoAggregateScore",
    "PublicDemoFormatStatus",
    "PublicDemoRiskBand",
    "ScenarioRuleEvidenceGate",
    "ScenarioRuleOutputPosture",
    "ScenarioRuleSignalDomain",
    "ScenarioRuleSurface",
    "ScenarioRuleSurfaceId",
    "SetupReadinessDimension",
    "SetupReadinessFinding",
    "SetupReadinessReport",
    "SetupReadinessSource",
    "TechnicalPdfNoteReference",
    "TechnicalPdfNoteReferenceDraft",
    "achieved_blueprint_delivery_mode",
    "blocked_public_demo_aggregate_score",
    "bounded_review_text",
    "build_blueprint_delivery_coverage",
    "build_client_safe_audit_report",
    "build_handoff_placeholder_manifest",
    "build_minimal_content_review",
    "build_public_demo_aggregate_score",
    "build_technical_pdf_note_references",
    "check_setup_readiness",
    "choose_catalog_field_seed_value",
    "classify_catalog_field_binding",
    "classify_note_surface",
    "client_blueprint_intake_manifest_as_dict",
    "client_blueprint_report_release_errors",
    "client_safe_audit_report_as_dict",
    "client_safe_audit_report_guard_errors",
    "coverage_regressed",
    "decode_text_content",
    "extract_json_object",
    "guard_blueprint_for_render",
    "is_unresolved_handoff_value",
    "linter_data_source_inventory",
    "linter_rule_surface_matrix",
    "make_linter_intake_requirements",
    "make_linter_promotion_readiness_errors",
    "make_linter_review_record_errors",
    "make_linter_rule_families",
    "make_linter_rule_family_by_id",
    "make_linter_rule_family_for_code",
    "make_linter_supported_codes",
    "mark_client_blueprint_source_deleted",
    "normalize_legacy_policy",
    "normalize_quality_profile",
    "note_guidance_statements",
    "note_surface_definition_by_kind",
    "note_surface_definitions",
    "public_demo_aggregate_score_as_dict",
    "reject_server_side_ai",
    "render_operator_report_preview",
    "scenario_rule_surface_by_id",
    "scenario_rule_surface_ids",
    "scenario_rule_surfaces",
    "setup_readiness_completion_blockers",
    "sync_linter_sqlite_audit",
    "technical_pdf_note_reference_code_map",
    "validate_assisted_delivery_capture",
    "validate_blueprint",
    "validate_client_blueprint_intake",
    "validate_content_review",
    "validate_linter_predicate_source",
    "validate_local_blueprint_import_parity",
)
