# Copyright (c) 2026 Alberto Villa Osorno.
# Licensed under the MIT License. See LICENSE in the project root.

"""Make non-raw evidence inventory contracts.

Boundary contract:
- Owns: structural checks for the private Make evidence inventory outside raw
specs.
- Must not: call Make.com, promote Golden business logic, or validate provider
credentials.
- Allows: local JSON reads that prove built-ins, manifests, Golden fixtures,
courses, SQL snapshots,
  and generated SQLite are classified with explicit evidence posture.
- Split when: the inventory becomes generated by a dedicated Make evidence
compiler.
- Merge when: Make Golden coverage tests own the same cross-surface inventory
assertions.
"""

from __future__ import annotations

import json
from typing import TYPE_CHECKING, cast

from languages.make.module_manifests import make_module_projector_manifest_paths

from tests.support.paths import repo_root

if TYPE_CHECKING:
    from pathlib import Path

    from tests.support.json_payloads import JsonObject


INVENTORY_PATH = "src/languages/make/data/non_raw_evidence_inventory.json"
GOLDEN_COVERAGE_PATH = "src/languages/make/data/golden/coverage.json"
RAW_SPEC_DIR = "temp/raw-specs-json"


def test_non_raw_make_evidence_inventory_is_private_and_offline() -> None:
    """The inventory is a private offline Make-adapter asset, not customer.

    copy.
    """
    inventory = _inventory()

    assert inventory["schema_version"] == 1
    assert inventory["asset"] == "make_non_raw_evidence_inventory"
    assert inventory["visibility"] == "private_engine_asset"
    assert inventory["raw_specs_excluded"] is True
    assert inventory["raw_spec_dir"] == RAW_SPEC_DIR
    assert inventory["safety_contract"] == {
        "live_make_called": False,
        "provider_api_call": False,
        "credential_value_transfer": False,
        "secret_output": False,
        "customer_facing": False,
    }


def test_non_raw_make_evidence_surfaces_are_classified_with_validation() -> (
    None
):
    """Every non-raw Make evidence surface declares why it exists and how it is.

    gated.
    """
    surfaces = _surfaces_by_id()

    assert {
        "make_native_semantics_matrix",
        "make_module_projector_manifests",
        "make_golden_corpus",
        "make_academy_courses",
        "make_expression_palette_observations",
        "make_default_manifest_coverage",
        "make_priority_module_families",
        "make_public_research_evidence",
        "make_roundtrip_reexport_parity_corpus",
        "make_db_snapshots",
        "make_knowledge_sqlite",
        "make_templates_manifest",
    } == set(surfaces)
    for surface in surfaces.values():
        assert surface["kind"] in {
            "engine_input",
            "evidence_only",
            "quarantine_source",
            "generated_sql_source",
            "generated_artifact",
        }
        assert surface["purpose"]
        assert surface["promotion_gate"]
        validation_tests = surface["validation_tests"]
        assert isinstance(validation_tests, list) and validation_tests, surface
        assert not str(surface["path"]).startswith(RAW_SPEC_DIR), surface

    assert surfaces["make_module_projector_manifests"]["kind"] == "engine_input"
    assert surfaces["make_golden_corpus"]["kind"] == "evidence_only"
    assert surfaces["make_default_manifest_coverage"]["kind"] == "engine_input"
    assert surfaces["make_priority_module_families"]["kind"] == "engine_input"
    assert surfaces["make_public_research_evidence"]["kind"] == "engine_input"
    assert (
        surfaces["make_roundtrip_reexport_parity_corpus"]["kind"]
        == "engine_input"
    )
    assert surfaces["make_academy_courses"]["file_count"] == 37
    assert surfaces["make_knowledge_sqlite"]["kind"] == "generated_artifact"


def test_non_raw_inventory_indexes_every_make_projector_manifest() -> None:
    """Built-ins and supported app projector manifests stay visible in the.

    inventory.
    """
    expected_manifest_paths = {
        _relative_path(path) for path in make_module_projector_manifest_paths()
    }
    records = _module_projector_contracts()
    indexed_manifest_paths = {str(record["path"]) for record in records}
    modules = {str(record["module"]) for record in records}

    assert indexed_manifest_paths == expected_manifest_paths
    assert {
        "builtin:BasicRouter",
        "builtin:Iterator",
        "builtin:BasicAggregator",
        "builtin:BasicRepeater",
        "datastore:AddRecord",
        "gateway:CustomWebHook",
        "slack:CreateMessage",
    } <= modules

    iterator = _module_contract("builtin:Iterator")
    iterator_aliases = {
        str(alias) for alias in cast("list[object]", iterator["aliases"])
    }
    assert "builtin:BasicFeeder" in iterator_aliases
    assert iterator["projector_kind"] == "array_iterator"


def test_non_raw_inventory_summarizes_golden_shape_evidence() -> None:
    """Golden analysis records shape evidence without overclaiming business.

    logic.
    """
    inventory = _inventory()
    golden = cast("JsonObject", inventory["golden_analysis"])
    coverage_entries = _read_json_list(_repo_root() / GOLDEN_COVERAGE_PATH)
    families = {
        str(record["family"]): int(cast("int", record["count"]))
        for record in cast("list[JsonObject]", golden["families"])
    }
    shape_counts = cast("JsonObject", golden["shape_evidence_counts"])

    assert golden["fixture_count"] == len(coverage_entries) == 130
    assert families == {"data/public/priority": 30, "data/public/top100": 100}
    assert int(cast("int", golden["unique_module_count"])) >= 150
    assert int(cast("int", shape_counts["route_containers"])) >= 1
    assert int(cast("int", shape_counts["filter_objects"])) >= 1
    assert int(cast("int", shape_counts["metadata_expect_objects"])) >= 1
    assert int(cast("int", shape_counts["metadata_restore_objects"])) >= 1
    assert int(cast("int", shape_counts["metadata_note_entries"])) >= 1
    not_authority_for = {
        str(item) for item in cast("list[object]", golden["not_authority_for"])
    }
    assert "Reusable customer business logic" in not_authority_for


def test_non_raw_inventory_tracks_make_native_alias_and_projector_gaps() -> (
    None
):
    """Golden-observed Make names resolve through manifests or remain explicit.

    gaps.
    """
    golden = cast("JsonObject", _inventory()["golden_analysis"])
    supported = cast(
        "list[JsonObject]", golden["supported_manifest_observations"]
    )
    gaps = cast("list[JsonObject]", golden["candidate_projector_gaps"])
    adapter_gaps = cast("list[JsonObject]", _inventory()["adapter_gaps"])

    assert any(
        observation["module"] == "builtin:BasicFeeder"
        and observation["manifest_module"] == "builtin:Iterator"
        for observation in supported
    )
    assert any(
        gap["module"] == "ai-local-agent:RunLocalAIAgent" for gap in gaps
    )
    assert any(
        gap["gap_id"] == "golden-observed-basic-feeder-alias"
        and gap["status"] == "covered_by_iterator_alias"
        for gap in adapter_gaps
    )


def _inventory() -> JsonObject:
    return _read_json_object(_repo_root() / INVENTORY_PATH)


def _read_json_object(path: Path) -> JsonObject:
    payload = cast("object", json.loads(path.read_text(encoding="utf-8")))
    assert isinstance(payload, dict), f"Expected JSON object: {path}"
    return cast("JsonObject", payload)


def _read_json_list(path: Path) -> list[object]:
    payload = cast("object", json.loads(path.read_text(encoding="utf-8")))
    assert isinstance(payload, list), f"Expected JSON list: {path}"
    return cast("list[object]", payload)


def _surfaces_by_id() -> dict[str, JsonObject]:
    surfaces = cast("list[JsonObject]", _inventory()["surfaces"])
    return {str(surface["surface_id"]): surface for surface in surfaces}


def _module_projector_contracts() -> list[JsonObject]:
    return cast("list[JsonObject]", _inventory()["module_projector_contracts"])


def _module_contract(module: str) -> JsonObject:
    for record in _module_projector_contracts():
        if record.get("module") == module:
            return record
    msg = f"Missing module projector contract: {module}"
    raise AssertionError(msg)


def _relative_path(path: Path) -> str:
    return path.relative_to(_repo_root()).as_posix()


def _repo_root() -> Path:
    return repo_root()
